### ISSUE TITLE
Error when going to process

### ISSUE THREAD

**Issue by fosterlynn** [valnet/valuenetwork#479]
Conditions not clear.  (Found when doing Breathing Games create plan from recipe.)

Traceback (most recent call last):

  File "/home/valnet/webapps/django/lib/python2.7/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)

  File "/home/valnet/webapps/django/valuenetwork/valuenetwork/valueaccounting/views.py", line 6347, in process_oriented_logging
    req.input_work_form_init = req.input_event_form_init(init=init)

  File "/home/valnet/webapps/django/valuenetwork/valuenetwork/valueaccounting/models.py", line 7793, in input_event_form_init
    qty_help = " ".join(["unit:", self.unit_of_quantity.abbrev, ", up to 2 decimal places"])

AttributeError: 'NoneType' object has no attribute 'abbrev'

**Comment by fosterlynn** [comment]
This was data - unit was entered in the unit of use instead of the unit in the resource types.  Still a bug, since unit should be required.  But not an urgent one.

**Comment by sqykly** [comment]
Fixing

**Comment by sqykly** [comment]
Suppose, though, I want to create a resource type "Eggs".  The unit will just be the quantity of eggs (you don't want to keep 2/3 of an egg laying around).  Rather than requiring a unit, how about adding a default Unit of quantity, items?  Is there something like that already?

**Comment by sqykly** [comment]
Fixed

**Comment by fosterlynn** [comment]
>Suppose, though, I want to create a resource type "Eggs". The unit will just be the quantity of eggs (you don't want to keep 2/3 of an egg laying around). Rather than requiring a unit, how about adding a default Unit of quantity, items? Is there something like that already?

That is "each".
