### ISSUE TITLE
Error on save customer order

### ISSUE THREAD

**Issue by fosterlynn** [valnet/valuenetwork#491]
transferBreakout branch: Entered an order in valdev from Digital Fab to Queens for some 3D printed parts.

Traceback (most recent call last):

  File "/home/valdev/webapps/django/lib/python2.7/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)

  File "/home/valdev/webapps/django/lib/python2.7/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)

  File "/home/valdev/webapps/django/valuenetwork/valuenetwork/valueaccounting/views.py", line 3073, in create_order
    user=request.user)

  File "/home/valdev/webapps/django/valuenetwork/valuenetwork/valueaccounting/models.py", line 3215, in add_customer_order_item
    ct.generate_producing_process(user, [], inheritance=None, explode=True)

  File "/home/valdev/webapps/django/valuenetwork/valuenetwork/valueaccounting/models.py", line 8816, in generate_producing_process
    process.explode_demands(demand, user, visited, inheritance)

  File "/home/valdev/webapps/django/valuenetwork/valuenetwork/valueaccounting/models.py", line 6230, in explode_demands
    order_item = output.order_item

AttributeError: 'NoneType' object has no attribute 'order_item'

**Comment by fosterlynn** [comment]
Note the order was actually created, guessing this is on trying to display the order schedule page?

**Comment by bhaugen** [comment]
I got the immediate problem solved and pushed but not the bigger problem - #496 

More to come...

**Comment by bhaugen** [comment]
Fixed.
